# from database import Base
from sqlalchemy import TIMESTAMP, Column, Integer, String, ForeignKey, text
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Posts(Base):
    __tablename__ = "posts"
    # primary key auto-generated by the database
    post_id = Column(Integer, primary_key=True, autoincrement=True)
    post_data = Column(String, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text('now()'))
    # ForeignKey to relate post to user
    user_id = Column(String, ForeignKey("users.user_id"), nullable=False)


class Users(Base):
    __tablename__ = "users"
    # use user_id (string) as primary key; remove redundant numeric "sn"
    user_id = Column(String, primary_key=True, unique=True, nullable=False)
    email = Column(String, nullable=False, unique=True)
    password = Column(String, nullable=False)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=text('now()'))

class Votes(Base):
    __tablename__ = "votes"
    user_id = Column(String, ForeignKey("users.user_id"), primary_key=True, nullable=False)
    post_id = Column(Integer, ForeignKey("posts.post_id"), primary_key=True, nullable=False)
