"""Checks:


Revision ID: 5b0b18e258c2
Revises: 83ef3cad1438
Create Date: 2025-12-22 22:12:54.887206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0b18e258c2'
down_revision: Union[str, Sequence[str], None] = '83ef3cad1438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_data',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('posts', 'post_data',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
